### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

### ISSUE THREAD

**Issue by pxc3113** [dundua/IG-Downloader#1]
$ python3 main.py
INFO:root:Opening config file.
INFO:root:Loading config file.
INFO:root:Initialize IG interface.
INFO:root:Get story tray.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): i.instagram.com
DEBUG:urllib3.connectionpool:https://i.instagram.com:443 "GET /api/v1/feed/reels_tray/ HTTP/1.1" 400 142
ERROR:root:Status Code Error.400
Traceback (most recent call last):
File "main.py", line 112, in 
main()
File "main.py", line 77, in main
storyresp = ig.getStories()
File "/home/zhiwei/Documents/IG-Downloader/instagram.py", line 65, in getStories
return self.getReelTray()
File "/home/zhiwei/Documents/IG-Downloader/instagram.py", line 45, in getReelTray
response.raise_for_status()
File "/home/zhiwei/.local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/feed/reels_tray/

**Comment by dundua** [comment]
This issue should now be fixed in commit 55a964d3797c34c8cbf107ca3db82d12895b813d

Delete your current config and generate a new one with the new cookies.
